name: 140journos
favicon: null
layout_spectrum: 0.75507
typography_spectrum: 1
title: 140journos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1db4c9'
    - '#f07930'
    - '#241205'
    - '#525e54'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
