name: 140journos
favicon: null
layout_spectrum: 0.9805954180192202
typography_spectrum: 0.2806175034493208
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6524091202300042
  lightness: 0.9354755841195583
  saturation: 0.7140592613723129
  rhythmicContrast: 0.5841497275978327
purpose: []
